// @musicFilesReducer
export const ADD_MUSIC_FILES = 'ADD_MUSIC_FILES';
export const REMOVE_MUSIC_FILE = 'REMOVE_MUSIC_FILE';
export const REMOVE_ALL_MUSIC_FILES = 'REMOVE_ALL_MUSIC_FILES';
export const UPDATE_MUSIC_FILES = 'UPDATE_MUSIC_FILES';
export const UPDATE_MUSIC_FILE = 'UPDATE_MUSIC_FILE';
export const UPDATE_MUSIC_FILES_ORDER = 'UPDATE_MUSIC_FILES_ORDER';

// @loadingReducer
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

// @dropzoneReducer
export const TURN_ON_DROPZONE = 'TURN_ON_DROPZONE';
export const TURN_OFF_DROPZONE = 'TURN_OFF_DROPZONE';
