const ADD_MUSIC_FILES = 'ADD_MUSIC_FILES';
const REMOVE_MUSIC_FILE = 'REMOVE_MUSIC_FILE';
const UPDATE_MUSIC_FILES = 'UPDATE_MUSIC_FILES';
export { ADD_MUSIC_FILES, REMOVE_MUSIC_FILE, UPDATE_MUSIC_FILES };
